# Project information
site_name: Swamp Fitness
site_url: https://swamp.fitness/
site_description: Swamp Fitness is a gymnasium for getting fit artistically.

# Repository
repo_name: Join us on Discord!
repo_url: https://discord.gg/VG2nGw4
edit_uri: ""

# Copyright
# copyright: "&copy; 2022 Swamp Fitness"

# Configuration
theme:
  name: material
  custom_dir: overrides

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top

  palette:
    scheme: slate
    primary: lime
    accent: pink

  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/discord

 # Customization 
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/VG2nGw4
extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
  - admonition
  - attr_list

# Page tree
nav:
  - Home: 'index.md'
  - Resources: 'resources.md'
  - VOD: 'vod.md'
  - Gym Staff: 'gym-staff.md'
  # - My Keyboards: 'kbd.md'
  # - Gacha Catalyst: 'gacha.md'